name: ci cache

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  avoid_reduncy:
    runs-on: ubuntu-20.04
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{github.token}}
  lint_client:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: "16.16.0"
          cache: "npm"
          cache-dependency-path: client/package-lock.json
      - name: Install dependencies
        run: cd client && npm ci
      - name: Lint
        run: cd client && npm run lint
  build_client:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: "16.16.0"
          cache: "npm"
          cache-dependency-path: client/package-lock.json
      - name: Install dependencies
        run: cd client && npm ci
      - name: Build
        run: cd client && npm run build
  test_client:
    needs: [lint_client, build_client]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: "16.16.0"
          cache: "npm"
          cache-dependency-path: client/package-lock.json
      - name: Install dependencies
        run: cd client && npm ci
      - name: Test
        run: cd client && npm test
  test_backend:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: "16.16.0"
          cache: "npm"
          cache-dependency-path: server/package-lock.json
      - name: Install dependencies
        run: cd server && npm ci
      - name: Test
        run: cd server && npm test
